local DialLayout = require('src/layout')

-- Dedicated panoramic design space. The renderer always fits this rectangle
-- uniformly into the current CSP app window, so no coordinate depends on the
-- user's resolution and the cluster can safely coexist with the square dials.
return {
  width = 1440,
  height = 500,

  leftCenterX = 175,
  rightCenterX = 1265,
  dialCenterY = 258,
  dialRadius = 174,
  tickRadius = 155,
  needleLength = 124,
  gaugeStart = math.rad(140),
  gaugeEnd = math.rad(400),
  digitalDialBarRadius = 161,
  digitalDialBarWidth = 8,
  digitalDialBarSegments = 36,
  digitalDialBarGap = 0.014,

  centerLeft = 420,
  centerRight = 1020,
  centerTop = 56,
  centerBottom = 285,
  centerBackdropChamfer = 24,
  centerBackdropBottomInset = 38,
  gearPodCenterX = 880,
  gearPodTop = 112,
  gearPodBottom = 244,
  gearPodHalfWidth = 92,
  gearPodChamfer = 14,
  leftFuelStatusOffset = -132,
  leftTcStatusOffset = -74,
  leftPitStatusOffset = 84,
  leftLimiterStatusOffset = 142,
  rightAbsStatusOffset = -142,
  rightLightsStatusOffset = -84,
  rightBrakeStatusOffset = 74,
  rightEngineStatusOffset = 132,
  indicatorLeftX = 460,
  indicatorRightX = 980,
  indicatorY = 260,

  rpmLeft = 448,
  rpmRight = 992,
  rpmTop = 82,
  rpmHeight = 24,
  rpmSegments = 34,
  rpmGap = 3,
  rpmStartFraction = DialLayout.digitalRpmAlertStartFraction,

  speedNeedleSpring = 55,
  speedNeedleDamping = 13,
  speedNeedleMaxVelocity = 2.2,
  rpmNeedleSpring = DialLayout.analogNeedleSpring,
  rpmNeedleDamping = DialLayout.analogNeedleDamping,
  rpmNeedleMaxVelocity = DialLayout.analogNeedleMaxVelocity,
  boostNeedleSpring = 72,
  boostNeedleDamping = 13.5,
  boostNeedleMaxVelocity = 2.8,

  ffbCenterX = 720,
  ffbCenterY = 408,
  ffbRadiusX = 150,
  ffbRadiusY = 72,
  ffbStart = math.rad(195),
  ffbEnd = math.rad(345),
  ffbSegments = 20,
  ffbNeedlePivotOffsetY = 32,
  ffbNeedleSpring = 70,
  ffbNeedleDamping = 12.5,
  ffbNeedleMaxVelocity = 2.6,
  historyLeft = 510,
  historyRight = 930,
  historyTop = 332,
  historyBottom = 470,
  historyGridRows = 4,
  historyGridColumns = 6,

  pedalTop = 260,
  pedalHeight = 170,
  pedalWidth = 22,
  pedalSegments = 12,
  pedalGap = 3,
  brakeX = 402,
  throttleX = 1022,
  boostStart = math.rad(135),
  boostEnd = math.rad(405),
  boostRadius = 65,
  flagLampSpacing = 12,
  flagLampSideOffset = 30,
  flagLampRadius = 4.5,

  indicatorPeriod = 0.42,
  flagBlinkPeriod = 0.42,
  shiftBlinkPeriod = 0.14,
  redlineBlinkPeriod = 0.12
}
