-- All coordinates are in a 620 x 620 design space. The renderer scales this
-- space uniformly. Keep the visual proportions here and tune its final size
-- from manifest.ini or the HUD scale setting.
return {
  baseSize = 620,
  centerX = 310,
  centerY = 304,
  viewportOffsetY = -10,

  outerRadius = 292,
  innerRadius = 266,
  dialRadius = 262,
  rpmRadius = 251,
  rpmTrackWidth = 25,
  rpmSegmentWidth = 17,
  rpmSegments = 36,
  rpmStart = math.rad(-210),
  rpmEnd = math.rad(30),

  bezelCutRadius = 276,
  bezelCutWidth = 14,
  turnIndicatorAngle = math.rad(16),
  turnIndicatorArcSpan = math.rad(10),
  warningArcSpan = math.rad(12),
  indicatorBlinkPeriod = 0.42,
  shiftBlinkPeriod = 0.14,
  redlineBlinkPeriod = 0.12,
  shiftZoneMinimumFraction = 0.14,

  analogDialOffsetY = 0,
  analogDialRadius = 258,
  analogTickRadius = 234,
  analogMinorTickCount = 45,
  analogNeedleLength = 204,
  analogNeedleWidth = 7,
  analogNeedleGlowWidth = 19,
  analogNeedleHaloWidth = 12,
  analogNeedleSpring = 130,
  analogNeedleDamping = 18,
  analogNeedleMaxVelocity = 3.8,
  analogGearOffsetY = -72,
  analogGearPodRadius = 34,
  analogGearFontSize = 52,
  analogSpeedOffsetY = 79,
  analogSpeedFontSize = 57,
  analogAuxLabelY = 464,
  analogAuxArcRadius = 206,
  analogAuxArcStart = math.rad(65),
  analogAuxArcEnd = math.rad(115),
  analogAuxArcWidth = 20,
  analogAuxSegments = 14,

  coreFrameHalfWidth = 112,
  coreFrameHalfHeight = 142,
  coreFrameChamfer = 22,
  coreHalfWidth = 100,
  coreHalfHeight = 108,
  coreChamfer = 18,
  coreOffsetY = 4,

  steeringY = 177,
  steeringHalfWidth = 66,

  pedalY = 235,
  pedalHeight = 148,
  pedalWidth = 25,
  brakeX = 145,
  throttleX = 440,

  speedY = 111,
  speedUnitY = 144,
  gearY = 272,
  gearFontSize = 148,
  rpmY = 392,
  rpmLabelY = 419,

  clutchLabelY = 441,
  clutchX = 269,
  clutchY = 454,
  clutchWidth = 82,
  clutchHeight = 6,

  electronicsX = 191,
  electronicsY = 473,
  electronicsWidth = 55,
  electronicsHeight = 52,
  electronicsGap = 6,

  shelfTopY = 461,
  shelfBottomY = 541,
  shelfTopHalfWidth = 140,
  shelfBottomHalfWidth = 106
}
